# Generated by Django 5.1.7 on 2025-04-05 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='business_category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='business_email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='business_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='business_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
