# Generated by Django 5.1.7 on 2025-04-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_askrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskRequest',
        ),
    ]
