# Generated by Django 5.1.7 on 2025-04-17 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_notifications_productrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.productrequest'),
        ),
    ]
