# Generated by Django 5.1.7 on 2025-04-18 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_notifications_related_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='businesses.business_profile'),
        ),
    ]
